name: Build Spyral

on:
  push:
      branches:
        - master
      paths:
        - src/main/webapp/resources/spyral/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#         with:
#           persist-credentials: false # required to install dependencies on github
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      
      # required to install dependencies on github
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      
      - name: Node install
        run: npm ci
        working-directory: src/main/webapp/resources/spyral
        
      - name: Build Spyral
        run: npm run-script build-spyral
        working-directory: src/main/webapp/resources/spyral
        
      - name: Commit JS files
        run: |
          git config --global user.name 'Voyant Tools'
          git config --global user.email 'voyanttools@users.noreply.github.com'
          git add src/main/webapp/resources/spyral/build/spyral.js src/main/webapp/resources/spyral/build/spyral.js.map
          git commit -m "chore: add Spyral build files"
          git push
